//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRunXMLParserTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestRunXMLParserTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        public static string FailSelectLabel {
            get {
                return ResourceManager.GetString("FailSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter and sort.
        /// </summary>
        public static string FilterAndSortStep {
            get {
                return ResourceManager.GetString("FilterAndSortStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate file.
        /// </summary>
        public static string GenerateFileStep {
            get {
                return ResourceManager.GetString("GenerateFileStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate JS.
        /// </summary>
        public static string GenerateJSBtn {
            get {
                return ResourceManager.GetString("GenerateJSBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate JS testrail selector script.
        /// </summary>
        public static string GenerateJSBtnToolTip {
            get {
                return ResourceManager.GetString("GenerateJSBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate XML.
        /// </summary>
        public static string GenerateXMLBtn {
            get {
                return ResourceManager.GetString("GenerateXMLBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate XML for rerun.
        /// </summary>
        public static string GenerateXMLBtnToolTip {
            get {
                return ResourceManager.GetString("GenerateXMLBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testrun XML parser tool.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open XML.
        /// </summary>
        public static string OpenFileBtn {
            get {
                return ResourceManager.GetString("OpenFileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open XML.
        /// </summary>
        public static string OpenFileBtnToolTip {
            get {
                return ResourceManager.GetString("OpenFileBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string OpenFileStep {
            get {
                return ResourceManager.GetString("OpenFileStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS.
        /// </summary>
        public static string PassSelectLabel {
            get {
                return ResourceManager.GetString("PassSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by folder.
        /// </summary>
        public static string SelectByFolderBtn {
            get {
                return ResourceManager.GetString("SelectByFolderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by screenshots folder. The currently selected cases will be reset..
        /// </summary>
        public static string SelectByFolderBtnToolTip {
            get {
                return ResourceManager.GetString("SelectByFolderBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting.
        /// </summary>
        public static string SelectingGroupBoxHeader {
            get {
                return ResourceManager.GetString("SelectingGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButtonTooltip {
            get {
                return ResourceManager.GetString("SettingsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingWindowLanguageLabel {
            get {
                return ResourceManager.GetString("SettingWindowLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListenerName:.
        /// </summary>
        public static string SettingWindowListenerNameLabel {
            get {
                return ResourceManager.GetString("SettingWindowListenerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string ShowingGroupBoxHeader {
            get {
                return ResourceManager.GetString("ShowingGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only selected.
        /// </summary>
        public static string ShowOnlySelectedLabel {
            get {
                return ResourceManager.GetString("ShowOnlySelectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIP.
        /// </summary>
        public static string SkipSelectLabel {
            get {
                return ResourceManager.GetString("SkipSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT.
        /// </summary>
        public static string SortLabel {
            get {
                return ResourceManager.GetString("SortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate JS.
        /// </summary>
        public static string WindowGenJSScriptCaption {
            get {
                return ResourceManager.GetString("WindowGenJSScriptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also the script was copied to the clipboard..
        /// </summary>
        public static string WindowGenJSScriptCopyToClipboardSuccessText {
            get {
                return ResourceManager.GetString("WindowGenJSScriptCopyToClipboardSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while generate JS file, read log file for get more details..
        /// </summary>
        public static string WindowGenJSScriptErrorText {
            get {
                return ResourceManager.GetString("WindowGenJSScriptErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JS script file generation and saving completed successfully. .
        /// </summary>
        public static string WindowGenJSScriptSuccessText {
            get {
                return ResourceManager.GetString("WindowGenJSScriptSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open XML file.
        /// </summary>
        public static string WindowGenOpenFileCaption {
            get {
                return ResourceManager.GetString("WindowGenOpenFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while open file, read log file for get more details..
        /// </summary>
        public static string WindowGenOpenFileErrorText {
            get {
                return ResourceManager.GetString("WindowGenOpenFileErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate XML.
        /// </summary>
        public static string WindowGenXMLCaption {
            get {
                return ResourceManager.GetString("WindowGenXMLCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while generate XML file, read log file for get more details..
        /// </summary>
        public static string WindowGenXMLErrorText {
            get {
                return ResourceManager.GetString("WindowGenXMLErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file generation and saving completed successfully..
        /// </summary>
        public static string WindowGenXMLSuccessText {
            get {
                return ResourceManager.GetString("WindowGenXMLSuccessText", resourceCulture);
            }
        }
    }
}
